# Use uma imagem base para servir arquivos estáticos
FROM nginx:alpine

# Copie os arquivos do frontend para o diretório padrão do nginx
COPY . /usr/share/nginx/html

# Exponha a porta padrão do nginx
EXPOSE 80
